#pragma once

enum EntityClusterMode
{
	ENTITY_CLUSTER_MODE_STATIC,
	ENTITY_CLUSTER_MODE_NON_STATIC
};

enum AutobuildingSpritePushDirection
{
	AUTOBUILDING_SPRITE_PUSH_DIRECTION_ROOF_Y,
	AUTOBUILDING_SPRITE_PUSH_DIRECTION_WALL_Z
};

enum PolygonDrawMode
{
	POLYGON_DRAW_MODE_DEPTH,
	POLYGON_DRAW_MODE_HEIGHT,
	POLYGON_DRAW_MODE_NORMAL_MAP,
	POLYGON_DRAW_MODE_GLOSS_MAP

};