#pragma once

enum EntityClusterMode
{
	ENTITY_CLUSTER_MODE_STATIC,
	ENTITY_CLUSTER_MODE_NON_STATIC
};

enum AutobuildingSpritePushDirection
{
	AUTOBUILDING_SPRITE_PUSH_DIRECTION_ROOF_Y,
	AUTOBUILDING_SPRITE_PUSH_DIRECTION_WALL_Z
};

enum PolygonDrawMode
{
	POLYGON_DRAW_MODE_DEPTH,
	POLYGON_DRAW_MODE_HEIGHT,
	POLYGON_DRAW_MODE_NORMAL_MAP,
	POLYGON_DRAW_MODE_GLOSS_MAP

};

enum PolygonVertexName
{
	POLYGON_VERTEX_NAME_RIGHT_UP,
	POLYGON_VERTEX_NAME_RIGHT_DOWN,
	POLYGON_VERTEX_NAME_LEFT_DOWN,
	POLYGON_VERTEX_NAME_LEFT_UP
};

enum CatchMethod
{
	CATCH_METHOD_BORDER_LEFT,
	CATCH_METHOD_BORDER_RIGHT,
	CATCH_METHOD_BORDER_DOWN,
	CATCH_METHOD_BORDER_UP,
	CATCH_METHOD_CORNER_LEFT_UP,
	CATCH_METHOD_CORNER_RIGHT_UP,
	CATCH_METHOD_CORNER_LEFT_DOWN,
	CATCH_METHOD_CORNER_RIGHT_DOWN,
	CATCH_METHOD_MID,
	CATCH_METHOD_MID_UP,
	CATCH_METHOD_BOTTOM,
	CATCH_METHOD_FREE,
};